spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  mvc:
    converters:
#      preferred-json-mapper: fastjson
    pathmatch:
      matching-strategy: ant_path_matcher

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gitstar?useSSL=false
    username: root
    password: "root"

server:
  error:
    include-stacktrace: never
    include-message: never
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      logic-delete-field: isDeleted   # 字段名（与实体类一致）
      logic-delete-value: 1           # 删除标记值
      logic-not-delete-value: 0       # 未删除标记值
